services:
  client:
    image: reactdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules