import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen w-full bg-white`}>
        {/* Hintergrundbild */}
        <img
          src="/img/background.webp"
          alt="Hero"
          className="fixed top-0 left-0 w-full h-full object-cover opacity-70 pointer-events-none mix-blend-lighten -z-10"
        />

        {/* Content-Wrapper */}
        <main className="flex min-h-screen w-full items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}


