import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body className="relative min-h-screen  bg-black bg-radial">
        {/* Hintergrundbild */}
        <img
          src="/img/smoke_2.avif"
          alt="Hero"
          className="absolute top-0 left-0 w-full h-full object-cover opacity-60 pointer-events-none mix-blend-lighten"
        />

        {/* Content-Wrapper */}
        <div className="relative z-10 w-[100%] mx-auto flex flex-col items-center pt-32 text-white min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}

